### ISSUE TITLE
Suggestion - incorporate innerHeight() rather or as well as height()

### ISSUE THREAD

**Issue by ando76** [PaulSpr/jQuery-Equal-Height-Columns#7]
innerHeight() is often what people will need. It incorporates the padding on elements within the blocks you want to equalize the height of.

**Comment by PaulSpr** [comment]
I understand what you mean. But isn't the padding on the elements usually the same?

I think that using box-sizing: border-box; will give you the same results since the padding is then included in the CSS height.

**Comment by PaulSpr** [comment]
I updated the plugin to 1.2 and you can now use innerHeight as well. Set it using:
    checkHeight: 'innerHeight'

My assumption (see previous answer) was very wrong. innerHeight works well with box-sizing: border-box
