### ISSUE TITLE
Feature request - equal heights based on elements on a row

### ISSUE THREAD

**Issue by mikeebee** [PaulSpr/jQuery-Equal-Height-Columns#8]
Hi!

Would it be possible to have it so that the script looks at elements in a row? Similar to this - http://css-tricks.com/equal-height-blocks-in-rows/

I think that would be the cherry on an already tasty cake!

Cheers,
Mike

**Comment by PaulSpr** [comment]
I'll probably need this for the project I'm working in now. So expect this to happen soon. I've figured out a pretty robust way to implement this. But as always with programming: we'll have to so how it actually works out!

**Comment by mikeebee** [comment]
Brilliant! Keep me posted Paul. Thanks!

**Comment by PaulSpr** [comment]
I took a while, but I've added the option to equalize per row. Use to option:
   equalizeRows: true

I hope you'll like it!
